apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: compulim.azurecr.io/server:latest
        livenessProbe:
          httpGet:
            path: /health.txt
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 3
          timeoutSeconds: 5
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      - name: app-compulim-info
        image: compulim.azurecr.io/app-compulim-info:latest
        livenessProbe:
          httpGet:
            path: /health.txt
            port: 4001
          initialDelaySeconds: 10
          periodSeconds: 3
          timeoutSeconds: 5
        ports:
        - containerPort: 4001
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      - name: app-pixelduet-com
        image: compulim.azurecr.io/app-pixelduet-com:latest
        livenessProbe:
          httpGet:
            path: /health.txt
            port: 4002
          initialDelaySeconds: 10
          periodSeconds: 3
          timeoutSeconds: 5
        ports:
        - containerPort: 4002
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: server
